SPYte/Areas/Admin/Models/CreateRole.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace SPYte.Areas.Admin.Models
{
    public class CreateRole
    {
        [Required]
        [Display(Name ="Role Name")]
        public string RoleName { get; set; }
    }
}

SPYte/Areas/Admin/Models/EditRole.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace SPYte.Areas.Admin.Models
{
    public class EditRole
    {
        public EditRole()
        {
            Users =  new List<string>();
        }
        public string Id { get; set; }
        [Required(ErrorMessage ="Role Name is required")]
        public string RoleName { get; set; }
        public List<string> Users { get; set; }
    }
}

SPYte/Areas/Admin/Controllers/AdministratorController.cs
using SPYte.Areas.Admin.Models;
using SPYte.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SPYte.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class AdministratorController : Controller
    {

        private readonly RoleManager<IdentityRole> roleManager;
        private readonly UserManager<ApplicationUser> userManager;

        public AdministratorController(RoleManager<IdentityRole> roleManager,
                                        UserManager<ApplicationUser> userManager)
        {
            this.roleManager = roleManager;
            this.userManager = userManager;
        }
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult CreateRole()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreateRole(CreateRole model)
        {
            if (ModelState.IsValid)
            {
                IdentityRole identityRole = new IdentityRole
                {
                    Name = model.RoleName
                };

                IdentityResult result = await roleManager.CreateAsync(identityRole);

                if (result.Succeeded)
                {
                    return Redirect("/Admin/Administrator/ListRole");
                }

                foreach (IdentityError error in result.Errors)
                {
                    ModelState.AddModelError("", error.Description);
                }

            }
            else
            {
                ViewBag.Error = "Model invalid";
            }

            return View(model);

        }

        [HttpGet]

        public IActionResult ListRole()
        {
            var roles = roleManager.Roles;
            return View(roles);
        }

        [HttpGet]
        public async Task<IActionResult> EditRole(string id)
        {
            var role = await roleManager.FindByIdAsync(id);
            if(role == null)
            {
                ViewBag.ErrorMessage = $"Role with id = {id} cannot be found";
                return View();
            }
            var model = new EditRole
            {
                Id = role.Id,
                RoleName = role.Name
            };

            foreach (var user in userManager.Users)
            {
                if(await userManager.IsInRoleAsync(user, role.Name))
                {
                    model.Users.Add(user.UserName);
                }

            }
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> EditRole(EditRole model)
        {
            var role = await roleManager.FindByIdAsync(model.Id);
            if (role == null)
            {
                ViewBag.ErrorMessage = $"Role with id = {model.Id} cannot be found";
                return View();
            }
            else
            {
                role.Name = model.RoleName;
                var result = await roleManager.UpdateAsync(role);

                if(result.Succeeded)
                {
                    return Redirect("/Admin/Administrator/ListRole");
                }
                else
                {
                    foreach (IdentityError error in result.Errors)
                    {
                        ModelState.AddModelError("", error.Description);
                    }
                }
                return View(model);
            }
            

        }

        [HttpGet]
        public async Task<IActionResult> EditUserRole(string roleId)
        {
            ViewBag.roleId = roleId;

            var role = await roleManager.FindByIdAsync(roleId);

            if (role == null)
            {
                ViewBag.ErrorMessage = $"Role with id = {roleId} cannot be found";
                return View();
            }
            ViewBag.roleName = role.Name;

            var model = new List<UserRole>();

            foreach(var user in userManager.Users)
            {
                var userRole = new UserRole
                {
                    UserId = user.Id,
                    UserName = user.UserName
                };
                if (await userManager.IsInRoleAsync(user, role.Name))
                {
                    userRole.IsSelected = true;
                }
                else
                {
                    userRole.IsSelected = false;
                }

                model.Add(userRole);

            }
            return View(model);
        }


        [HttpPost]
        public async Task<IActionResult> EditUserRole(List<UserRole> model, string roleId)
        {
            var url = "/Admin/Administrator/EditRole?id=" + roleId;
            var role = await roleManager.FindByIdAsync(roleId);

            if (role == null)
            {
                ViewBag.ErrorMessage = $"Role with id = {roleId} cannot be found";
                return View();
            }
            for(int i = 0;i<model.Count;i++)
            {
                var user =  await userManager.FindByIdAsync(model[i].UserId);

                IdentityResult result = null;

                if(model[i].IsSelected && !(await userManager.IsInRoleAsync(user, role.Name)))
                {
                    result = await userManager.AddToRoleAsync(user, role.Name);
                }
                else if(!model[i].IsSelected && await userManager.IsInRoleAsync(user, role.Name))
                {
                    result = await userManager.RemoveFromRoleAsync(user, role.Name);
                }
                else
                {
                    continue;
                }

                if(result.Succeeded)
                {
                    if (i < (model.Count - 1))
                        continue;
                    else
                    {
                        
                        return Redirect(url);
                    }
                        
                }

            }
            return Redirect(url);
        }
    }
}

SPYte/Areas/Admin/Views/Administrator/CreateRole.cshtml
@model SPYte.Areas.Admin.Models.CreateRole

@{
    ViewData["Title"] = "Create Role";
}

@ViewBag.Error
<div class="row">
    <div class="col-md-4">
        <form method="post">
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="RoleName" class="control-label"></label>
                <input asp-for="RoleName" class="form-control" />
                <span asp-validation-for="RoleName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create Role" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

SPYte/Areas/Admin/Views/Administrator/EditRole.cshtml
@model EditRole

@{
    ViewBag.Title = "Edit Role";
}
@ViewBag.ErrorMessage



<form method="post" class="mt-3">
    <div class="form-group row">
        <label asp-for="Id" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <input asp-for="Id" disabled class="form-control" />
        </div>
    </div>
    <div class="form-group row">
        <label asp-for="RoleName" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <input asp-for="RoleName" class="form-control" />
            <span asp-validation-for="RoleName" class="text-danger"></span>
        </div>
    </div>
    <div asp-validation-summary="All" class="text-danger"></div>

    <div class="form-group row">
        <div class="col-sm-10">
            <button type="submit" class="btn btn-primary">Update</button>
            <a asp-action="ListRole" asp-area="Admin" asp-controller="Administrator" class="btn btn-primary">Cancel</a>
        </div>
    </div>


    <div class="card">
        <div class="card-header">
            <h3>Users in this role</h3>
        </div>
        <div class="card-body">
            @if (Model.Users.Any())
            {
                foreach (var user in Model.Users)
                {
                    <h5 class="card-title">
                        @user
                    </h5>
                }
            }
            else
            {
                <h5 class="card-title">
                    None at the moment
                </h5>
            }
        </div>
        <div class="card-footer">
            <a asp-action="EditUserRole" asp-area="Admin" asp-controller="Administrator" asp-route-roleId="@Model.Id" class="btn btn-primary">Add or remove users</a>
        </div>
    </div>
</form>

<div class="row">
</div>

SPYte/Areas/Admin/Views/Administrator/EditUserRole.cshtml
@model List<UserRole>

@{
    var roleId = ViewBag.roleId;
    var roleName = ViewBag.roleName;
}
@ViewBag.ErrorMessage
<form method="post">
    <div class="card">
        <div class="card-header">
            <h2>Add or remove users from @roleName role</h2>
        </div>
        <div class="card-body">
            @for (int i = 0; i < Model.Count; i++)
            {
                <div class="form-check m-1">
                    <input type="hidden" asp-for="@Model[i].UserId" />
                    <input type="hidden" asp-for="@Model[i].UserName" />
                    <input asp-for="@Model[i].IsSelected" class="form-check-input" />
                    <label class="form-check-label" asp-for="@Model[i].IsSelected">
                        @Model[i].UserName
                    </label>
                </div>
            }
        </div>
        <div class="card-footer">
            <input type="submit" value="Update" class="btn btn-primary" />
            <a asp-action="EditRole" asp-controller="Administrator" asp-area="Admin" asp-route-id="@roleId">Cancel</a>
        </div>
    </div>
</form>

SPYte/Areas/Admin/Views/Administrator/Index.cshtml
@{
    ViewData["Title"] = "Create Role";
}
Hi

SPYte/Areas/Admin/Views/Administrator/ListRole.cshtml
@model IEnumerable<IdentityRole>

@{
    ViewData["Title"] = "List Role";
}
<h3>
    All role
</h3>

@if (Model.Any())
{
    <a class="btn btn-primary mb-3" style="width:auto" href='/Admin/Administrator/CreateRole'>
        Create Role
    </a>
    foreach (var role in Model)
    {

        <div class="card mb-3">
            <div class="card-header">
                Role Id: @role.Id
            </div>
            <div class="card-body">
                <h5 class="card-title">@role.Name</h5>
            </div>
            <div class="card-footer">
                <a asp-area="Admin" asp-controller="Administrator" asp-action="EditRole" asp-route-id="@role.Id" class="btn btn-primary">
                    Edit
                </a>
                <a href="#" class="btn btn-primary">Delete</a>
            </div>
        </div>
    }

}
else
{
    <div class="card">
        <div class="card-header">
            No roles created yet
        </div>
        <div class="card-body">
            <h5 class="card-title">
                Use the button below to create new role
            </h5>
            <a class="btn btn-primary" style="width:auto" href='/Admin/Administrator/CreateRole'>
                Create Role
            </a>
        </div>
    </div>
}